# Erzeugt schrift_daten.cpp aus den Open-Sans-TTFs (ohne Python, auf allen
# drei Plattformen). Aufruf aus CMakeLists.txt beim Konfigurieren:
#   aeroacars_schrift_einbetten(<ausgabe.cpp> NAME1 datei1 NAME2 datei2 …)
function(aeroacars_schrift_einbetten ausgabe)
    set(inhalt "// Erzeugt von werkzeuge/schrift_einbetten.cmake - nicht von Hand aendern.\n")
    string(APPEND inhalt "// Open Sans, Copyright 2020 The Open Sans Project Authors, SIL OFL 1.1.\n")
    string(APPEND inhalt "#include \"schrift_daten.h\"\n\nnamespace aeroacars {\nnamespace schrift_daten {\n")
    set(args ${ARGN})
    list(LENGTH args n)
    math(EXPR letzter "${n} - 1")
    foreach(i RANGE 0 ${letzter} 2)
        math(EXPR j "${i} + 1")
        list(GET args ${i} name)
        list(GET args ${j} datei)
        file(READ "${datei}" hex HEX)
        string(LENGTH "${hex}" hexlaenge)
        math(EXPR bytes "${hexlaenge} / 2")
        string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," hex "${hex}")
        string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){24})" "\\1\n" hex "${hex}")
        string(APPEND inhalt "extern const unsigned char ${name}[];\nconst unsigned char ${name}[] = {\n${hex}\n};\n")
        string(APPEND inhalt "extern const size_t ${name}_GROESSE;\nconst size_t ${name}_GROESSE = ${bytes};\n\n")
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${datei}")
    endforeach()
    string(APPEND inhalt "}  // namespace schrift_daten\n}  // namespace aeroacars\n")
    # Nur schreiben, wenn sich etwas ändert (sonst baut jedes Konfigurieren neu).
    if(EXISTS "${ausgabe}")
        file(READ "${ausgabe}" alt)
        if(alt STREQUAL inhalt)
            return()
        endif()
    endif()
    file(WRITE "${ausgabe}" "${inhalt}")
endfunction()
